pipeline {
  agent {
    docker { image 'ubuntu' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'echo "hellow"'
      }
    }
  stages {
    stage ('Test2')
	steps {
	sh 'echo "helloooo"'
}	
}

  }
}
