pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Clone the GitHub repository
                    git 'https://github.com/mannakod/Jenkins-Zero-To-Hero.git'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Your build commands here
                    sh 'echo "Building the project"'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Your test commands here
                    sh 'echo "Running tests"'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Your deployment commands here
                    sh 'echo "Deploying the project"'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded! Yay!'
        }
        failure {
            echo 'Pipeline failed! Boo!'
        }
    }
}
